routes/admin.php
<?php

Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/dashboard', 'AdminController@index')->name('admin.home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
// 	return view('layouts.app');
// });


Route::get('/about', function(){

	// return 'About me';
	return view('about');

});

Route::get('post/{id}', function(\illuminate\Http\Request $request, $id){
	$post = \App\Models\Post::findOrFail($id);

	return response()->json([
		'title' => $post->title,
		'body' => $post->body,
		'published' => $post->createdAt()
	]);
});

// Route::middleware('test')->get('/custom', function(){
Route::get('/custom/{id}', function(\illuminate\Http\Request $request, $id){
	
	if(!auth()->check()){
		throw new \App\Exceptions\HackerAlertException;
	}
	return \App\Models\User::findOrFail($id);


	// $tsp = resolve('medium-php-sdk');
	// dd($tsp);
});

Route::get('/queue-test', 'QueueController@index');

Route::get('/', 'QuestionController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('cruds', 'CrudController@index');
Route::get('cruds/create', 'CrudController@create')->name('cruds.index');
Route::post('cruds/store', 'CrudController@store')->name('cruds.store');

Route::resource('questions', 'QuestionController')->except(['show']);

Route::get('questions/{slug}','QuestionController@show')->name('questions.show');

Route::resource('questions.answers', 'AnswerController')->except(['create', 'show']);

Route::post('answers/{answer}/accept', 'AcceptAnswerController')->name('answers.accept');

Route::post('questions/{question}/favorite', 'FavoriteQuestionController@store')->name('questions.favorite');

Route::delete('questions/{question}/favorite', 'FavoriteQuestionController@distroy')->name('questions.unfavorite');

Route::post('questions/{question}/vote', 'VoteQuestionController')->name('questions.vote');

Route::post('answers/{answer}/vote', 'VoteAnswerController')->name('answers.vote');

Route::get('solutions/{id}', 'ProblemController@solutions');


// File upload
Route::get('file/upload', 'FileUploadController@fileCreate');
Route::post('file/store', 'FileUploadController@fileStore');
Route::post('file/delete', 'FileUploadController@fileDestroy');

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Traits\VotableTrait;

class Answer extends Model
{
    use VotableTrait;
    
    protected $guarded = [];

    protected $appends = ['created_date', 'body_html', 'status', 'is_best'];

    public function question(){
        return $this->belongsTo(Question::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public static function boot(){

        parent::boot();

        static::created(function($answer){
            $answer->question->increment('answers_count');
            \Log::info('Req=App/Models/Answer::boot static::created called');
       });

       static::deleted(function ($answer){
        $question = $answer->question;
        $question->decrement('answers_count');

        if($question->best_answer_id == $answer->id){
            $question->best_answer_id = null;
            $question->save();
        }

        \Log::info('Req=App/Models/Answer::boot satic::deleted called');

        });

    }

    public function getBodyHtmlAttribute(){
        return clean(\Parsedown::instance()->text($this->body));
    }

    public function getCreatedDateAttribute(){
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute(){
        return $this->isBest() ? 'vote-accepted' : '';
        // return 'vote-accepted';
    }

    public function getIsBestAttribute(){
        return $this->isBest();
    }

    public function isBest(){
        return $this->id == $this->question->best_answer_id;
    }


}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use Illuminate\Http\Request;
use App\Models\Question;

class AnswerController extends Controller
{
     
    public function __construct(){
        
        $this->middleware('auth')->except('index');
    }

    public function index(Question $question){
        
        return $question->answers()->with('user')->simplePaginate(3);

    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Question $question, Request $request)
    {
        $request->validate([
            'body' => 'required|max:1000'
        ]);

        // $answer = $question->answers()->create(['body' => $request->body, 'user_id' => auth()->id() ]);
        $answer = $question->answers()->create($request->validate([
            'body' => 'required'
        ])+ ['user_id' => \Auth::id()]);

        if($request->expectsJson()){
            return response()->json([
                'message' => 'Your answer has been submitted successfully',
                'answer' => $answer->load('user')
            ]);
        }

        return back()->with('success', 'Your answer has been submitted successfully.');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question, Answer $answer)
    {
        \Log::info('Req=AnswerController@edit called');

        $this->authorize('update', $answer);

        return view('answers.edit', compact('question', 'answer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question, Answer $answer)
    {

        \Log::info('Req=AnswerController@update called');

        $this->authorize('update', $answer);

        $answer->update($request->validate([
            'body' => 'required|max:1000'
        ]));

        if($request->expectsJson()){
            return response()->json([
                'message'=> 'Your answer has been updated',
                'body_html' => $answer->body_html
            ]);
        }
        return redirect()->route('questions.show', $question->slug)->with('success', 'Your answer has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question, Answer $answer)
    {

        \Log::info('Req=AnswerController@destroy called');

        $this->authorize('delete', $answer);

        $answer->delete();

        if(request()->expectsJson()){
            return response()->json([
                'message' => 'Your answer has been deleted successfully'
            ]);
        }
        return back()->with('success', 'Your answer has been deleted successfully.');

    }
}

resources/views/answers/_answer.blade.php
<answer :answer="{{ $answer }}" inline-template>
<div class="media post">
    <div class="d-flex flex-column vote-controls">
        {{-- @include('shared._vote', [
            'model' => $answer,
            'model_name' => 'Answer'
        ]) --}}
        <vote :model="{{$answer}}" :name="'answer'"> </vote>
    </div>
    <div class="media-body">
        
        <form v-if="editing" @submit.prevent="update">
            <div class="form-group">
                <textarea v-model="body" rows="10" class="form-control"></textarea>
            </div>
            <button class="btn btn-primary" :disabled="isInvalid"> Update </button>
            <button class="btn btn-outline-secondary" @click="cancel" type="button"> Cancel </button>
        </form>
        <div v-else>
            <div v-html="bodyHtml"></div>
        
            <div class="row">
                <div class="col-4">
                    <div class="d-flex">
                        @can('update', $answer)
                        <a @click.prevent="edit" class="btn btn-outline-secondary mr-2" >Edit</a>
                        @endcan
                        @can('delete', $answer)
                       
                            <button class="btn btn-outline-danger" type="submit" @click="destroy"> Delete </button>
                      
                        @endcan
                    </div>
                </div>
                
                <div class="col-4"> </div>
                <div class="col-4">
                    <user-info :model="{{$answer}}" label="Answered"></user-info>
                </div>
            </div>
        </div>
    </div>
</div>
</answer>

resources/views/answers/_create.blade.php
<div class="row mt-4"> <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h2> Answer The Question</h2>
            </div>

            <div class="card-body">
                <form action="{{route('questions.answers.store', $question->id) }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="body">Your Answer:</label>
                        <textarea name="body" id="body" cols="30" rows="10" class="form-control @error('body') is-invalid @enderror"> {{ old('body') }}</textarea>

                        @error('body')
                        <div class="invalid-feedback">
                            <strong> {{ $message }}</strong>
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-outline-secondary">Submit </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/answers/_index.blade.php
@if($answersCount > 0)
<div class="row mt-5" v-cloak>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title mt-2">
                    <h2> {{ $answersCount ." ". str_plural('Answer', $answersCount) }}</h2>
                </div>
            </div>
            
            @include('layouts._message')
            
            @foreach($answers as $answer)
                @include('answers._answer')            
            @endforeach
        </div>
    </div>
</div>
@endif

resources/views/answers/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                     Question Answer for the title  <strong> {{ $question->title }}  </strong>
                </div>

                    <div class="card-body">
                        <form action="{{route('questions.answers.update', [$question->id, $answer->id])}}" method="POST">
                            @csrf
                            @method('PATCH')

                            <div class="form-group">
                                <label for="body">Your Answer</label>
                                <textarea name="body" id="body" cols="30" rows="10" class="form-control @error('body') is-invalid @enderror">{{ old('body', $answer->body) }} </textarea>

                                @error('body')
                                <div class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <button class="btn btn-outline-secondary form-control" type="submit">Submit</button>
                            </div>
                        </form>
                   </div>
            </div>
        </div>
    </div>
</div>
@endsection()