routes/admin.php
<?php

Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/dashboard', 'AdminController@index')->name('admin.home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
// 	return view('layouts.app');
// });


Route::get('/about', function(){

	// return 'About me';
	return view('about');

});

Route::get('post/{id}', function(\illuminate\Http\Request $request, $id){
	$post = \App\Models\Post::findOrFail($id);

	return response()->json([
		'title' => $post->title,
		'body' => $post->body,
		'published' => $post->createdAt()
	]);
});

// Route::middleware('test')->get('/custom', function(){
Route::get('/custom/{id}', function(\illuminate\Http\Request $request, $id){
	
	if(!auth()->check()){
		throw new \App\Exceptions\HackerAlertException;
	}
	return \App\Models\User::findOrFail($id);


	// $tsp = resolve('medium-php-sdk');
	// dd($tsp);
});

Route::get('/queue-test', 'QueueController@index');

Route::get('/', 'QuestionController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('cruds', 'CrudController@index');
Route::get('cruds/create', 'CrudController@create')->name('cruds.index');
Route::post('cruds/store', 'CrudController@store')->name('cruds.store');

Route::resource('questions', 'QuestionController')->except(['show']);

Route::get('questions/{slug}','QuestionController@show')->name('questions.show');

Route::resource('questions.answers', 'AnswerController')->except(['create', 'show']);

Route::post('answers/{answer}/accept', 'AcceptAnswerController')->name('answers.accept');

Route::post('questions/{question}/favorite', 'FavoriteQuestionController@store')->name('questions.favorite');

Route::delete('questions/{question}/favorite', 'FavoriteQuestionController@distroy')->name('questions.unfavorite');

Route::post('questions/{question}/vote', 'VoteQuestionController')->name('questions.vote');

Route::post('answers/{answer}/vote', 'VoteAnswerController')->name('answers.vote');

Route::get('solutions/{id}', 'ProblemController@solutions');


// File upload
Route::get('file/upload', 'FileUploadController@fileCreate');
Route::post('file/store', 'FileUploadController@fileStore');
Route::post('file/delete', 'FileUploadController@fileDestroy');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Auth;
use App\Models\Traits\VotableTrait;

class Question extends Model
{
    use VotableTrait;
    
    protected $guarded = [];
    // protected $fillable = ['title', 'body'];

    protected $appends = ['created_date', 'favorites_count', 'body_html', 'is_favorited'];
    
    public function user() {
        return $this->belongsTo(User::class);
    }    

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = str_slug($value);
    }

    // public function setBodyAttribute($value)
    // {
    //     $this->attributes['body'] = clen($value);
    // }

    public function getUrlAttribute()
    {
        return route("questions.show", $this->slug);
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute()
    {
        if ($this->answers_count > 0) {
            if ($this->best_answer_id) {
                return "answered-accepted";
            }
            return "answered";
        }
        return "unanswered";
    }

    public function getBodyHtmlAttribute()
    {
        return clean($this->bodyHtml());
    }

    public function answers()
    {
        return $this->hasMany(Answer::class)->orderBy('votes_count', 'DESC');
    }

    public function acceptBestAnswer(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function favorites()
    {
        return $this->belongsToMany(User::class, 'favorites')->withTimestamps(); //, 'question_id', 'user_id');
        // return $this->belongsToMany(User::class, 'favorites', 'question_id', 'user_id')->withTimestamps(); //, 'question_id', 'user_id');

    }

    public function getIsFavoritedAttribute()
    {
        return $this->isFavorited();
    }
   
    public function isFavorited()
    {
        if(auth()->check()){

            return $this->favorites()->where('user_id', Auth()->user()->id)->count() > 0;
        }
        return null;
        // dd($this->favorites()->where('user_id', request()->user()->id())->count() > 0);
    }


    public function getFavoritesCountAttribute()
    {
        return $this->favorites->count();
    }    

    public function getExcerptAttribute()
    {
        return $this->excerpt(250);
    }

    public function excerpt($length)
    {
        return str_limit(strip_tags($this->bodyHtml()), $length);
    }

    private function bodyHtml()
    {
        return \Parsedown::instance()->text($this->body);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Question;
use Illuminate\Http\Request;
use App\Http\Requests\StoreQuestionPost;

class QuestionController extends Controller
{
    
    public function __construct(){
        $this->middleware('auth')->except('index', 'show');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        \Log::info('Req=QuestionController@index Called');
        
        $questions = Question::with('user')->latest()->paginate(5);
     
        return view('questions.index', compact('questions'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        \Log::info('Req=QuestionController@crate Called');

        $question = new Question();
        
        return view('questions.create', compact('question'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreQuestionPost $request)
    {
        \Log::info('Req=QuestionController@store called');
        
        $request->user()->questions()->create($request->only('title', 'body'));
        
        return redirect()->route('questions.index')->with('success','Your question has been published.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        \Log::info('Req=QuestionController@show Called');

        $question->increment('views');

        return view('questions.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        \Log::info('Req=QuestionControler@edit Called');
        
        // if(\Gate::disallow('update-question', $question)){
        //     return abort(404);
        // }

            $this->authorize('update', $question);

            return view('questions.create', compact('question'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(StoreQuestionPost $request, Question $question)
    {
       \Log::info('Req=QuestionControler@update Called');
        
       $this->authorize('update', $question);

      $question->update($request->only('title', 'body'));

      if($request->expectsJson()){
          return response()->json([
              'message' => "Your question has been update successfully",
              'body_html' => $question->body_html
          ]);
      }

        return redirect()->route('questions.index')->with('success', 'Your question has been update successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        
        \Log::info('Req=QuestionController@destroy Called');

        $this->authorize('delete', $question);

        $question->delete();

        if(request()->expectsJson()){
            return response()->json([
                'message' => "Your question has been deleted successfully"
            ]);
        }
  

        return redirect()->route('questions.index')->with('success', 'Your quesiton has been deleted successfully.');
    }
}

resources/views/questions/_excerpt.blade.php
<div class="media post">
    <div class="d-flex flex-column counters">
        <div class="vote">
            <strong> {{ $question->votes_count }} </strong> {{ str_plural('Vote', $question->votes_count) }}
        </div>
        
        <div class="status {{ $question->status }}">
            <strong> {{ $question->answers_count }}</strong> {{ str_plural('Answer', $question->answers_count) }}
        </div>
        
        <div class="view">
            {{ $question->views ." ". str_plural('View', $question->views) }}
        </div>
        
    </div>
    
    <div class="media-body">
        <div class="d-flex align-items-center">
            <h3 class="mt-0"><a href="{{ $question->url }}"> {{ $question->title }} </a></h3>
            <div class="ml-auto">
                @can('update', $question)
                <a href="{{ route('questions.edit', $question->id) }}" class="btn btn-outline-info"> Edit</a>
                @endcan
                @can('delete', $question)
                <form class="form-delete" action="{{route('questions.destroy', $question->id)}}" method="POST">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-outline-danger" onclick="confirm('Are you Sure?');">Delete</button>
                </form>
                @endcan
            </div>
        </div>
        
        <p class="lead">
            Asked by <a href="{{ $question->user->url }}">{{ $question->user->name }} </a>
            <small class="text-muted"> {{ $question->created_date }} </small>
        </p>
        {!! $question->excerpt(250) !!}
    </div>
    
</div>

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-contain-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>Ask Question</h2>
                        <div class="ml-auto">
                            <a href="{{route('questions.index') }}" class="btn btn-outline-secondary"> Back All Question</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ $question->exists ? route('questions.update', $question->id) : route('questions.store') }}" method="POST">
                            @csrf
                            @if($question->exists)
                            @method('PUT')
                            @endif
                        <div class="form-group">
                            <label for="question_title">Question Title</label>
                            <input type="text" name="title" value="{{ $question->exists ? $question->title : old('title') }}" id="question_title" class="form-control @error('title') is-invalid @enderror">

                            @error('title')
                                <div class="invalid-feedback">
                                <strong>{{ $message }}</strong>  
                                 </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="questions_body">Qustion Body</label>
                            <textarea name="body" id="questions_body" class="form-control @error('body') is-invalid @enderror" rows="10">{{ old('body') }}</textarea>

                            @error('body')
                            <div class="invalid-feedback">
                            <strong>{{ $message }} </strong> 
                            </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <input type="submit" name="submit" class="btn btn-outline-primary btn-large"> 
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justfy-content-center">
        <div class="col-md-12">
            <div class="card">

                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>All Questions</h2>
                        <div class="ml-auto">
                            <a href="{{ route('questions.create') }}" class="btn btn-secondary"> Ask Question </a>
                        </div>
                    </div>
                </div>

                <div class="card-body">

                        @include('layouts._message')

                        @forelse($questions as $question)
                            @include('questions._excerpt')    
                        @empty
                            <div class="alert alert-warning">
                                <strong>Sorry,</strong> There are no Questions here.
                            </div>
                        @endforelse

                       {{ $questions->links() }}

                </div>

            </div>
        </div>
    </div>
</div>

@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
<question-page :question="{{$question}}"></question-page>
@endsection