routes/admin.php
<?php

Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/dashboard', 'AdminController@index')->name('admin.home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
// 	return view('layouts.app');
// });


Route::get('/about', function(){

	// return 'About me';
	return view('about');

});

Route::get('post/{id}', function(\illuminate\Http\Request $request, $id){
	$post = \App\Models\Post::findOrFail($id);

	return response()->json([
		'title' => $post->title,
		'body' => $post->body,
		'published' => $post->createdAt()
	]);
});

// Route::middleware('test')->get('/custom', function(){
Route::get('/custom/{id}', function(\illuminate\Http\Request $request, $id){
	
	if(!auth()->check()){
		throw new \App\Exceptions\HackerAlertException;
	}
	return \App\Models\User::findOrFail($id);


	// $tsp = resolve('medium-php-sdk');
	// dd($tsp);
});

Route::get('/queue-test', 'QueueController@index');

Route::get('/', 'QuestionController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('cruds', 'CrudController@index');
Route::get('cruds/create', 'CrudController@create')->name('cruds.index');
Route::post('cruds/store', 'CrudController@store')->name('cruds.store');

Route::resource('questions', 'QuestionController')->except(['show']);

Route::get('questions/{slug}','QuestionController@show')->name('questions.show');

Route::resource('questions.answers', 'AnswerController')->except(['create', 'show']);

Route::post('answers/{answer}/accept', 'AcceptAnswerController')->name('answers.accept');

Route::post('questions/{question}/favorite', 'FavoriteQuestionController@store')->name('questions.favorite');

Route::delete('questions/{question}/favorite', 'FavoriteQuestionController@distroy')->name('questions.unfavorite');

Route::post('questions/{question}/vote', 'VoteQuestionController')->name('questions.vote');

Route::post('answers/{answer}/vote', 'VoteAnswerController')->name('answers.vote');

Route::get('solutions/{id}', 'ProblemController@solutions');


// File upload
Route::get('file/upload', 'FileUploadController@fileCreate');
Route::post('file/store', 'FileUploadController@fileStore');
Route::post('file/delete', 'FileUploadController@fileDestroy');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Auth;
use App\Models\Traits\VotableTrait;

class Question extends Model
{
    use VotableTrait;
    
    protected $guarded = [];
    // protected $fillable = ['title', 'body'];

    protected $appends = ['created_date', 'favorites_count', 'body_html', 'is_favorited'];
    
    public function user() {
        return $this->belongsTo(User::class);
    }    

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = str_slug($value);
    }

    // public function setBodyAttribute($value)
    // {
    //     $this->attributes['body'] = clen($value);
    // }

    public function getUrlAttribute()
    {
        return route("questions.show", $this->slug);
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute()
    {
        if ($this->answers_count > 0) {
            if ($this->best_answer_id) {
                return "answered-accepted";
            }
            return "answered";
        }
        return "unanswered";
    }

    public function getBodyHtmlAttribute()
    {
        return clean($this->bodyHtml());
    }

    public function answers()
    {
        return $this->hasMany(Answer::class)->orderBy('votes_count', 'DESC');
    }

    public function acceptBestAnswer(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function favorites()
    {
        return $this->belongsToMany(User::class, 'favorites')->withTimestamps(); //, 'question_id', 'user_id');
        // return $this->belongsToMany(User::class, 'favorites', 'question_id', 'user_id')->withTimestamps(); //, 'question_id', 'user_id');

    }

    public function getIsFavoritedAttribute()
    {
        return $this->isFavorited();
    }
   
    public function isFavorited()
    {
        if(auth()->check()){

            return $this->favorites()->where('user_id', Auth()->user()->id)->count() > 0;
        }
        return null;
        // dd($this->favorites()->where('user_id', request()->user()->id())->count() > 0);
    }


    public function getFavoritesCountAttribute()
    {
        return $this->favorites->count();
    }    

    public function getExcerptAttribute()
    {
        return $this->excerpt(250);
    }

    public function excerpt($length)
    {
        return str_limit(strip_tags($this->bodyHtml()), $length);
    }

    private function bodyHtml()
    {
        return \Parsedown::instance()->text($this->body);
    }
}

resources/views/shared/_accept.blade.php
@can('accept', $answer)
<a onclick="event.preventDefault(); document.getElementById('accept-answer-{{ $answer->id }}').submit()" 
    title="Mark this as a best answer" class="{{ $answer->status }} mt-4">
    <i class="fas fa-check fa-2x"></i>
</a>

<form action="{{route('answers.accept', $answer->id)}}" id="accept-answer-{{$answer->id}}" method="POST" style="display:none;">
    @csrf
</form>
@else
    @if($answer->is_best)
    <a title="This is the best answer" class="{{ $answer->status }} mt-4"> <i class="fas fa-check fa-2x"></i> </a>
    @endif
@endcan

resources/views/shared/_author.blade.php
<span class="text-muted"> {{ $label .' '. $model->created_date }} </span>
<div class="media mt-1">
        <a href="{{ $model->user->url }}">
            <img src="{{ $model->user->gravatar }}" alt="{{ $model->user->name }}">
        </a>
    <div class="media-body m-1">
        <a href="{{ $model->user->url }}"> {{ $model->user->name }} </a>
    </div>
</div>

resources/views/shared/_favorite.blade.php
<a onclick="event.preventDefault(); document.getElementById('favorite-form-{{$question->id}}').submit();" title="Click to mark as favorite question (Click again to undo)" 
    class="favorite mt-2 {{$question->isFavorite() > 0 ? 'favorited' : 'off'  }}">  <i class="fas fa-star fa-2x"></i>
    <span class="favorites-count"> {{ $question->favorite_count }} </span>
 </a>

 <form action="{{ $question->isFavorite() ? route('questions.favorite', $question->id) : route('questions.unfavorite', $question->id)}}" id="favorite-form-{{$question->id}}" method="POST">
    @csrf
    @if($question->isFavorite())
    @method('delete')
    @endif
</form>

resources/views/shared/_vote.blade.php
<a title="This {{$model_name}} is useful" class="vote-up {{ Auth::guest() ? 'off' : ''}}" onclick="event.preventDefault(); document.getElementById('{{$model_name}}-vote-up-{{$model->id}}').submit();">
<i class="fas fa-caret-up fa-3x"> </i>
</a>

<form action="{{ $model_name == 'question' ? route('questions.vote', $model->id) : route('answers.vote', $model->id)}}" id="{{$model_name}}-vote-up-{{$model->id}}" method="POST" style="display:none;">
    @csrf
    <input type="hidden" name="vote" value="1">
</form>

<span class="votes-count "> {{ $model->votes_count }} </span>

<a title="This {{$model_name}} is not useful" class="vote-down {{Auth::guest() ? 'off' : ''}}" onclick="event.preventDefault(); document.getElementById('{{$model_name}}-vote-down-{{$model->id}}').submit();">
    <i class="fas fa-caret-down fa-3x"></i>
</a>

<form action="{{ $model_name == 'question' ? route('questions.vote', $model->id) : route('answers.vote', $model->id)}}" id="{{$model_name}}-vote-down-{{$model->id}}" method="POST" style="display:none;">
    @csrf
    <input type="hidden" name="vote" value="-1">
</form>

@if($model == $question)
    <favorite :question="{{$model}}"> </favorite>
{{-- @include('shared._favorite') --}}
@elseif($model == $answer)
    <accept :answer="{{$model}}"> </accept>
    {{-- @include('shared._accept') --}}
@endif


    
    